import { jsPDF } from 'jspdf';

export const applyDocumentFooter = (doc: jsPDF) => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const pageCount = (doc.internal as any).getNumberOfPages ? (doc.internal as any).getNumberOfPages() : 1;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);

    const dateStr = new Date().toLocaleString('en-IN');
    
    // Left: System Info
    doc.text('Generated by MJ Healthcare ERP', 15, pageHeight - 10);
    doc.text(`Generated Date & Time: ${dateStr}`, 15, pageHeight - 6);
    
    // Center: Notice
    doc.text('This is a computer-generated document.', pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.text('© MJ Healthcare Pvt. Ltd.', pageWidth / 2, pageHeight - 6, { align: 'center' });
    
    // Right: Page Numbers
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
  }
};
